'use client';

import React from 'react';
import './globals.css';
import { Provider } from 'react-redux';
import store from './store/store';

export const metadata = {
  title: 'Bilderbuchgenerator',
  description: 'Generated by create next app',
};

/*
export default function RootLayout({ children }) {
  /* return (
    <html lang="en">
      <body className={raleway.className}>
        <Hero />
        <main className="container">{children}</main>
      </body>
    </html>
  ); */
/*
  return (
    <html lang="de">
      <body>
        <Register />
      </body>
    </html>
  );
} */

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      {(children)}
    </Provider>
  );
}
